[package]
name = "file_transform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.4.18",features = ["derive"]}
aes = "0.8.3"
block-modes = "0.9.1"
flate2 = "1.0.28"
